### ISSUE TITLE
Vehicles do not respawn

### ISSUE THREAD

**Issue by devicewhite** [BenBurak/samp-vehicle-streamer#3]
After a while the vehicles start not reappearing.
Example: create a vehicle, let some time pass, then when you pass by where it should appear it is not there, then some more time passes if

**Comment by nexquery** [comment]
I haven't been working on the plugin for a long time. I need help from the community to make it a stable plugin.

For example:
- A code that further optimizes the flow of vehicles.
- What should happen when the vehicle limit is reached in a region.
- Too much testing of the plugin.

These examples can be multiplied.
